#!/bin/bash
sed -i 's/^gpgcheck=1/gpgcheck=0/' /etc/yum.repos.d/CentOS-Base.repo
sed -i 's/^enabled=0/enabled=1/' /etc/yum.repos.d/CentOS-Base.repo

sed -i 's/^gpgcheck=1/gpgcheck=0/' /etc/yum.repos.d/CentOS-Sources.repo
sed -i 's/^enabled=0/enabled=1/' /etc/yum.repos.d/CentOS-Sources.repo

sudo yum install -y yum-utils
sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
sudo yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
sudo systemctl enable --now docker
echo "INSTALL DOCKER COMPLETE"

