#!/bin/bash

if [ "$1" == "centos" ]; then 
    sed -i 's/^gpgcheck=1/gpgcheck=0/' /etc/yum.repos.d/CentOS-Base.repo
    sed -i 's/^enabled=0/enabled=1/' /etc/yum.repos.d/CentOS-Base.repo

    sed -i 's/^gpgcheck=1/gpgcheck=0/' /etc/yum.repos.d/CentOS-Sources.repo
    sed -i 's/^enabled=0/enabled=1/' /etc/yum.repos.d/CentOS-Sources.repo

    sudo yum install -y yum-utils
    sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    sudo yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    sudo systemctl enable --now docker
    echo "INSTALL DOCKER (CENTOS) COMPLETE"

elif [ "$1" == "rhel9" ]; then
    sudo yum remove docker docker-client docker-client-latest docker-common docker-latest docker-latest-logrotate docker-logrotate docker-engine podman runc
    sudo yum install -y yum-utils
    sudo yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    sudo yum install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o docker-compose
    sudo mv docker-compose /usr/local/bin && sudo chmod +x /usr/local/bin/docker-compose
    sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
    sudo systemctl enable --now docker
    echo "INSTALL DOCKER (RHEL9) COMPLETE"
else
    echo "UNKNOWN ARGUMENT!!"
fi
